name: Composer
on: 
  push:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  updatecheck:
    name: Updatecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1
        with:
          comand: show -lo
